name: Terraform CI/CD

on:
  push:
    branches: [main]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}
  REGION: us-central1
  REPO_NAME: docker-repo
  IMAGE_NAME: iris-api

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Enable Required APIs
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT }}
        gcloud services enable \
          artifactregistry.googleapis.com \
          run.googleapis.com \
          composer.googleapis.com \
          dataflow.googleapis.com \
          bigquery.googleapis.com \
          compute.googleapis.com \
          monitoring.googleapis.com \
          serviceusage.googleapis.com

    - name: Build and Push Docker Image
      run: |
        cd api
        gcloud auth configure-docker ${REGION}-docker.pkg.dev
        docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest .
        docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest
        cd ..

    - name: Terraform Init and Apply
      run: |
        terraform init -reconfigure \
          -backend-config="bucket=gcp-state-terraform" \
          -backend-config="prefix=terraform/state"

        terraform apply -auto-approve \
          -var="project_id=${PROJECT_ID}" \
          -var="location=${REGION}" \
          -var="service_account_email=terraform-gcp-pipeline@${PROJECT_ID}.iam.gserviceaccount.com"
