# File: .github/workflows/deploy.yml
name: Terraform CI/CD

on:
  push:
    branches: [main]

env:
  PROJECT_ID: terraform-inf
  REGION: us-central1
  REPO_NAME: docker-repo
  IMAGE_NAME: iris-api
  SERVICE_ACCOUNT: terraform-gcp-pipeline@terraform-inf.iam.gserviceaccount.com

jobs:
  deploy:
    name: Build & Deploy on GCP
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ env.PROJECT_ID }}
        export_default_credentials: true

    - name: Enable Required GCP APIs
      run: |
        gcloud services enable \
          artifactregistry.googleapis.com \
          run.googleapis.com \
          composer.googleapis.com \
          dataflow.googleapis.com \
          bigquery.googleapis.com \
          compute.googleapis.com \
          monitoring.googleapis.com \
          serviceusage.googleapis.com \
          iamcredentials.googleapis.com

    - name: Build and Push Docker Image
      working-directory: ./api
      run: |
        gcloud auth configure-docker ${REGION}-docker.pkg.dev
        docker build -t ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest .
        docker push ${REGION}-docker.pkg.dev/${PROJECT_ID}/${REPO_NAME}/${IMAGE_NAME}:latest

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        terraform init -reconfigure \
          -backend-config="bucket=gcp-state-terraform" \
          -backend-config="prefix=terraform/state"

    - name: Terraform Apply
      run: |
        terraform apply -auto-approve \
          -var="project_id=${PROJECT_ID}" \
          -var="service_account_email=${SERVICE_ACCOUNT}"
